module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.4.2-stable-13.09
cabal-file: project.cabal
hidden-packages: ''
version: 1
extra-packages: ! 'Hackage: smallcheck 1.1.1

  Hackage: tf-random 0.5

  Hackage: QuickCheck 2.7.6

  Hackage: loop 0.2.0

  Hackage: matrix 0.3.4.0

  Hackage: ansi-terminal 0.6.1.1

  Hackage: transformers 0.4.1.0

  Hackage: transformers-compat 0.3.3.4

  Hackage: optparse-applicative 0.9.1.1

  Hackage: regex-tdfa-rc 1.1.8.3

  Hackage: tasty 0.8.1.3

  Hackage: tasty-hunit 0.9

  Hackage: tasty-quickcheck 0.8.1

  Hackage: tasty-smallcheck 0.8

  Hackage: permutation 0.5.0.4'
ghc-args: []
excluded-modules:
- src/Test/TestWeyl.hs
